title: "M4GiK Software Portfolio"
email: "michal.szczygiel@wp.pl"
description: ""
baseurl: ""
url: "https://m4gik.github.io"
author: "Michał Szczygieł"
repository: "M4GiK/M4GiK.github.io"
layouts_dir: _layouts
exclude:
  - src
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor